### ISSUE TITLE
Error when deploy due to glassfish Tyrus

### ISSUE THREAD

**Issue by hotcacao** [kklisura/chrome-devtools-java-client#1]
Hi @kklisura,

Thank you for your great project. However I failed to deploy and get below exception trace:

> javax.servlet.ServletException: java.lang.InstantiationException: org.glassfish.tyrus.server.TyrusServerConfiguration
> 	at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:88)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.InstantiationException: org.glassfish.tyrus.server.TyrusServerConfiguration
> 	at java.lang.Class.newInstance(Class.java:427)
> 	at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:74)
> 	... 8 more
>
> 
> Caused by: java.lang.NoSuchMethodException: org.glassfish.tyrus.server.TyrusServerConfiguration.<init>()
> 	at java.lang.Class.getConstructor0(Class.java:3082)
> 	at java.lang.Class.newInstance(Class.java:412)
> 	... 9 more

After checking your source code, I figure out that you only need Glassfish Tyrus to run UnitTest.
So can you add `<scope>test</scope>` into your pom.xml file? Or make a separated module for testing.

Thank you in advance.

**Comment by kklisura** [comment]
Thank you for brining this to my attention. I've updated pom, with `tyrus-container-grizzly-server` now as `test` dependency, I've also replaced `tyrus-client` with `tyrus-container-grizzly-client` since it's still needed for websocket. I've published this change as snapshot version `1.2.1-SNAPSHOT`, so you can give it a try.
