### ISSUE TITLE
Logging is broken.

### ISSUE THREAD

**Issue by FlameDuck** [kklisura/chrome-devtools-java-client#12]
Hi,

It seems like something is causing com.github.kklisura.cdt.services.impl.WebSocketServiceImpl` from respecting Slf4j settings, as it is always logging with the DEBUG level, regardless of Slf4j settings, filling up the log with a lot of needless noise.

I am unsure what is causing this.

Kind regards,
Mikkel Løkke

**Comment by kklisura** [comment]
Hi, thanks for using this library. 
Unfortunately I was not able to reproduce this. Could you share some more information? What logging framework and SLF4J binding are you using? How is the logging framework being configured?

Thanks.

**Comment by FlameDuck** [comment]
Hey, thanks for wrtting it. It's really useful. It turns out it was my shitty spring configuration that was broken. You can ignore it.
