### ISSUE TITLE
Full Page Screenshot

### ISSUE THREAD

**Issue by raharrison** [kklisura/chrome-devtools-java-client#13]
Running the screenshot example in https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-examples/src/main/java/com/github/kklisura/cdt/examples/TakeScreenshotExample.java it seems that it only captures a screenshot of the active viewport (by default 800x600?).

Any way to get a screenshot of the entire page?

**Comment by kklisura** [comment]
Hi, thanks for using this library.

You can either:

- pass custom argument to chrome for larger viewport, by using following (for headless):

```java
    final ChromeArguments chromeArguments = ChromeArguments.defaults(true)
        .additionalArguments("window-size", "1920,1080")
        .build();
    final ChromeService chromeService = launcher.launch(chromeArguments);
```

- ...or capture a screenshot given a viewport definition:

```java
          Viewport viewport = new Viewport();
          viewport.setScale(1d);

          // Set an viewport screenshot offset
          viewport.setX(0d);
          viewport.setY(0d);

          // Set a width, height of a page to take screenshot at
          viewport.setWidth(960d);
          viewport.setHeight(3000d);

          dump("screenshot.png", page.captureScreenshot(
              CaptureScreenshotFormat.PNG,
              100,
              viewport,
              Boolean.TRUE
          ));
```

**Comment by raharrison** [comment]
Hi - I was thinking more like capturing the entire webpage not just what's visible in the viewport (as if scrolling from top to bottom and capturing everything).

e.g. Puppeteer has the fullPage: true option, is there an alternative of that?

**Comment by kklisura** [comment]
Hi @raharrison, the `viewport` is an argument to a `captureScreenshot` method of the dev-tools, so it can be set to a dimensions that are outside of the visible viewport. Be in mind that this is a low-level library for interacting with chrome. Puppeteer, besides giving access to low-lever interactions, adds a bit higher level interactions as well - ie as in your example proving a fullPage: true option. This high level functionality will in turn calculate dimensions of the page by using `Page.getLayoutMetrics` and then it will call the method `page.captureScreenshot` (as in example I've sent above) and will provide a viewport with specified values (this is called clip in a Puppeteer source code, you can see it here https://github.com/GoogleChrome/puppeteer/blob/9ef23b17542cc630e502fcf6689bf6b20fa9911b/lib/Page.js#L884)

Anyways... I've added a full example on how to capture full page screenshot. You can check it out here https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-examples/src/main/java/com/github/kklisura/cdt/examples/FullPageScreenshotExample.java.

Kind regards,
Kenan

**Comment by raharrison** [comment]
Thanks, works great!
