### ISSUE TITLE
Web socket client not annotated with @ClientEndpoint

### ISSUE THREAD

**Issue by clubLowlow** [kklisura/chrome-devtools-java-client#2]
Tomcat 9, Java 8, getting the following error

javax.websocket.DeploymentException: Cannot use POJO class [com.github.kklisura.cdt.services.impl.WebSocketServiceImpl$1] as it is not annotated with @ClientEndpoint
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:122)
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:86)
	at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.create(WebSocketServiceImpl.java:76)
	at com.github.kklisura.cdt.services.impl.ChromeServiceImpl.lambda$new$3(ChromeServiceImpl.java:94)
	at com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:176)
	at com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:161)

**Comment by hariprasaadssalem** [comment]
In com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:86), instead of new Endpoint(), creating a CustomClientEndpoint class with @ClientEndpoint annotation and using it in WEB_SOCKET_CONTAINER.connectToServer seems to fix the problem.

```
// CustomClientEndpoint.java
@ClientEndpoint
public final class CustomClientEndpoint extends Endpoint {
  private static final Logger LOGGER = LoggerFactory.getLogger(CustomClientEndpoint.class);

  public CustomClientEndpoint() {}

  @Override
  public void onOpen(Session session, EndpointConfig config) {
    LOGGER.info("Connected to ws server");
  }
}

// WebSocketServiceImpl.java:86
session = WEB_SOCKET_CONTAINER.connectToServer(
                    CustomClientEndpoint.class,
                    uri);
```

@kklisura Can you check.

**Comment by kklisura** [comment]
Thanks @clubLowlow for reporting this issue and thanks @hariprasaadssalem for suggesting a fix.  👍 🙏 

I was able to fix this and release it as snapshot version, `1.3.1-SNAPSHOT`, so you can give it a try before releasing as new version.

```xml
<dependency>
  <groupId>com.github.kklisura.cdt</groupId>
  <artifactId>cdt-java-client</artifactId>
  <version>1.3.1-SNAPSHOT</version>
</dependency>
```

If there's nothing more I'll be releasing this as `1.3.1` in next few days.

**Comment by hariprasaadssalem** [comment]
@kklisura I validated with 1.3.1-SNAPSHOT... Things are working fine...
Thank you for this wonderful project. :)

**Comment by ytzhangFTD** [comment]
> Thanks @clubLowlow for reporting this issue and thanks @hariprasaadssalem for suggesting a fix. 👍 🙏
> 
> I was able to fix this and release it as snapshot version, `1.3.1-SNAPSHOT`, so you can give it a try before releasing as new version.
> 
> ```
> <dependency>
>   <groupId>com.github.kklisura.cdt</groupId>
>   <artifactId>cdt-java-client</artifactId>
>   <version>1.3.1-SNAPSHOT</version>
> </dependency>
> ```
> 
> If there's nothing more I'll be releasing this as `1.3.1` in next few days.

sorry about that!I can't find the `1.3.1-SNAPSHOT` on mvnrepository.Have you released the version?

>

**Comment by kklisura** [comment]
> > Thanks @clubLowlow for reporting this issue and thanks @hariprasaadssalem for suggesting a fix. 👍 🙏
> > I was able to fix this and release it as snapshot version, `1.3.1-SNAPSHOT`, so you can give it a try before releasing as new version.
> > ```
> > <dependency>
> >   <groupId>com.github.kklisura.cdt</groupId>
> >   <artifactId>cdt-java-client</artifactId>
> >   <version>1.3.1-SNAPSHOT</version>
> > </dependency>
> > ```
> > If there's nothing more I'll be releasing this as `1.3.1` in next few days.
> 
> sorry about that!I can't find the `1.3.1-SNAPSHOT` on mvnrepository.Have you released the version?
> 
> >

You probably need to add snapshot repository to your pom:
```xml
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
```
in order to fetch a snapshot version.

...or you can wait couple of hours for me to release version `1.3.1`. I'll be doing it later tonight.
