### ISSUE TITLE
Way to force close the tab or chrome window

### ISSUE THREAD

**Issue by varun85gupta** [kklisura/chrome-devtools-java-client#28]
Hi, 

I recently came across the issue where the chrome tab just hangs and becomes non-responsive. In such cases the close() on chrome tab doesn't work. 
However, I can manually go to the task manager of chrome and kill the window from there. 

Is it possible to provide a way to force close the window or tab ?

**Comment by fragaLY** [comment]
@varun85gupta , I think that is the way you are looking for:
`        final ChromeService service = ChromeServiceHolder.CHROME_SERVICE.getService();
        final ChromeTab tab = service.createTab();
        final ChromeDevToolsService devToolsService = service.createDevToolsService(tab);
        //some logic
        service.closeTab(tab);`

**Comment by kklisura** [comment]
@varun85gupta I've just released `2.1.0` which fixes some issues that can result in hang of the API. Could you check again if this solves your issue? Thanks.
