### ISSUE TITLE
Impossible to create a pdf using #onLoadEventFired

### ISSUE THREAD

**Issue by fragaLY** [kklisura/chrome-devtools-java-client#29]
I faced with a problem using the primer of pdf generation using #onLoadEventFired event.
The problem is in page generation using ReactJS. Components rendering takes for about a 2 seconds but the PDF output looks like a loading page:

![image](https://user-images.githubusercontent.com/19571660/67691219-4395e200-f9af-11e9-94cc-7557a80c09d8.png)

As a workaround, we are creating the CustomEvent at #componentDidMount ReactJS component lifecycle step with name, for instance "mounted":
`...
event = new CustomEvent(typeArg, customEventInit);
dispatchEvent(event)
...`

This event is logging at the absolutely correct time to the page for a generation. Nevertheless, no one event of Page instance handles this custom event. Moreover, I've tried to handle this event using DOM events. Unfortunately, no one handler helps me.
I've been searching a lot for a decision and found that using Puppeteer we may use #exposeFunction method of page object to handle simply custom events.

Could you please help me to find the correct solution?
I've used the code sample that you suggested for pdf generation.

Thank you.

**Comment by kklisura** [comment]
Hi,

you can add binding via `addBinding` method on the `Runtime`. This will expose binding name on the window object in the page. In this following example I'm adding `onCdtContinue` binding, so `window.onCdtContinue` will be a function that can be invoked on web page side, `window.onCdtContinue('')`. After invoking that, `onBindingCalled` listener argument will be executed:

```java
    final Runtime runtime = devToolsService.getRuntime();
    runtime.enable();

    page.onLoadEventFired(event -> {
      runtime.addBinding("onCdtContinue");
      runtime.onBindingCalled(new EventHandler<BindingCalled>() {
        @Override
        public void onEvent(BindingCalled event) {
          // Make sure event name is onCdtContinue
        }
      });
    });
```

**Comment by fragaLY** [comment]
@kklisura,

We found the other one solution, simply talking this is a workaround.

We are adding to localStorage the item in #componentDidMount method:
`localStorage.addItem("ready", "1");`

After this, we are able to handle it using the DOMStorage:
`final Page page = devToolsService.getPage();
        page.enable();

        final DOMStorage domStorage = devToolsService.getDOMStorage();
        domStorage.enable();
        domStorage.onDomStorageItemAdded(event -> {
            if (ChromeLocalStorageItem.READY.getItem().equalsIgnoreCase(event.getKey())) {
            //pdf generation logic
            devToolsService.close();
}
        });

        page.navigate(url);`

**Comment by fragaLY** [comment]
Thank you.
