### ISSUE TITLE
Unable to set timezone using Emulation

### ISSUE THREAD

**Issue by varun85gupta** [kklisura/chrome-devtools-java-client#35]
I was trying out the Emulation interface to set the timezone in the Chrome tab. However, Either I am not using it properly or it doesn't work. 

```
Emulation emulation = chromeDevToolsService.getEmulation();
emulation.setTimezoneOverride("inccu"); 
```
The string is taken from [here](https://github.com/unicode-org/cldr/blob/master/common/bcp47/timezone.xml) as mentioned [here](https://developers.google.com/maps/documentation/timezone/intro#Requests)

I verified using this code in chrome JS console. My machine is UTC timezone and I tried to change the timezone to `Asia/Calcutta Asia/Kolkata` using above API :
```
var date = new Date();
console.log(date);
```
The time still shows the same as the host OS

**Comment by kklisura** [comment]
Would you mind trying `Asia/Calcutta`, I'm not sure `inccu` is a valid timeZoneId. Chrome supported timezones are here https://chromium.googlesource.com/chromium/deps/icu52/+/ff8353094b0b29f2d50059c452d15bbf0a84c0ad/source/data/misc/metaZones.txt

```
final Emulation emulation = devToolsService.getEmulation();
emulation.setTimezoneOverride("Asia/Calcutta");
```

**Comment by varun85gupta** [comment]
I tried this as well. It still doesn't work

**Comment by varun85gupta** [comment]
I tried it and it didn't work initially . However, if I set the emulation before the page load, it worked. Thanks for the suggestion.
