### ISSUE TITLE
chromeProcess termination with exit code 1

### ISSUE THREAD

**Issue by harihandle** [kklisura/chrome-devtools-java-client#4]
@kklisura Thanks again for this wonderful project. 👍 

Sometimes the chromeProcess in ChromeLauncher terminates with exit code 1 when waiting for Page onLoadEvent to occur.

As of now, It is not possible to know when this happens.

Can you expose a method in ChromeLauncher to address this.

```
public boolean hasExited() {
    try {
        chromeProcess.exitValue();
        return true;
    } catch(IllegalThreadStateException e) {
        return false;
    }
}
```

**Comment by kklisura** [comment]
Thank you for using this library. I've added the `exitValue` and `isAlive` methods to `ChromeLauncher`, which are just proxy to underlaying process `exitValue` and `isAlive` methods. The implementation of the `isAlive` method is similar to what you described. This is already part of the latest release.
