### ISSUE TITLE
printToPDF support

### ISSUE THREAD

**Issue by Vad1mo** [kklisura/chrome-devtools-java-client#5]
Nice work 👏  

Would it be possible to support `printToPDF` I was looking into the code but couldn't figure out how to add this functionality.

**Comment by kklisura** [comment]
Hi! I've just added an example on how printing to pdf can be achived, you can look at it here https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-examples/src/main/java/com/github/kklisura/cdt/examples/PrintingPageToPdf.java. 

This is very low level library for interacting with chrome and I'm in a process of writing higher level library that could make these things a bit clearer and easier.
