### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by davidchu** [kklisura/chrome-devtools-java-client#54]
Is it possible to create a new release of this library?  The last release is more than 1 year old and the protocol has been updated since.

**Comment by sinaa** [comment]
@kklisura any chance a re-sync with devtools protocol master and mvn release would be possible?

Happy to assist in any way if you currently have little/no time to maintain this project.

**Comment by sinaa** [comment]
@kklisura many thanks for the release, 🎉  I can see this is now pushed to maven: https://mvnrepository.com/artifact/com.github.kklisura.cdt/cdt-java-client/3.0.0

@davidchu I believe this can issue be closed now.

**Comment by davidchu** [comment]
Thank you!
