### ISSUE TITLE
Not working with JDK 11 (SOLVED)

### ISSUE THREAD

**Issue by Ansorre** [kklisura/chrome-devtools-java-client#7]
Hi, thank you for this wonderful project.
I've been using it for some month, but today I had to switch to JDK 11 and it stopped working.
After some research I was able to let it work again. 
It was necessary to upgrade javassist to the latest version: javassist-3.24.1-GA
instead of the not working (with JDK 11) version: javassist-3.22.0-GA
which is referenced in the project pom.xml file
Just to let you know.
Thank you again.

**Comment by kklisura** [comment]
Thank you for using this library. I've updated javassist library, as you noted. Latest version has been released. 🎉

**Comment by Ansorre** [comment]
Thank you very very much. 😀
