### ISSUE TITLE
Config for ChromeDevToolsService not used

### ISSUE THREAD

**Issue by selevt** [kklisura/chrome-devtools-java-client#9]
When getting an instance of the ChromeDevToolsService from the ChomeService the provided configuration is not used.

```
chromeService.createDevToolsService(tab, devToolsConfig);
```

Instead of using the passed configuration, it always uses a new instance of the configuration, see:
https://github.com/kklisura/chrome-devtools-java-client/blob/master/cdt-java-client/src/main/java/com/github/kklisura/cdt/services/impl/ChromeServiceImpl.java#L179

As a workaround it is possible to set the config on the returned service with reflection.

**Comment by kklisura** [comment]
Hi, thanks for using this library and thanks for contributing! I've merged the PR you've submitted and I'll be releasing it soon. 👍
